# Generated by Django 5.2.15 on 2026-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='capacity_mode',
            field=models.CharField(choices=[('warn', 'Warn'), ('block', 'Block')], default='warn', max_length=10),
        ),
    ]
