# Generated by Django 5.2.15 on 2026-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='goal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cycle Goal'),
        ),
    ]
